### ISSUE TITLE
Contribute to PyHPO

### ISSUE THREAD

**Issue by anergictcell** [TheJacksonLaboratory/hpo-toolkit#6]
Hi,

I have just stumbled upon your hpo-toolkit library and see that it has some very nice features. I have been working on a similar library, which is already quite stable, extendable and very well tested: [PyHPO](https://pypi.org/project/pyhpo/) ([Docs](https://centogene.github.io/pyhpo/)). I was wondering if you think it would make sense to combine our efforts and work on one library together.

**Comment by ielis** [comment]
Hi @anergictcell 
thanks for reaching out. I am not sure, however, that combining efforts would work out, at least in the short term. I went through `PyHPO`, and on the first take, I see several incompatibilities between my desired API and what you already have. To make both of us happy, we would have to introduce a decent number of breaking changes into your code, which would upset your users. Moreover, `hpo-toolkit` is here primarily to support other ongoing projects and I need the library to evolve quickly. Due to the time constraint, again, I think it would be just too too hard to keep both of us happy.

In the longer term, we can aim for a union of our interests and to build a library with all bells and whistles for work with HPO.

Thanks a lot for understanding and all the best,
Daniel

**Comment by anergictcell** [comment]
Hi,

thanks for the feedback. Makes total sense. PyHPO is not evolving quickly anymore, so it would be difficult to support your projects.
I'll keep watching hpo-toolkit, looks like an exciting project.

Cheers,
Jonas

**Comment by abearab** [comment]
I've been using pyHPO since last year and I just saw hpo-toolkit. Great job on both side!

**Comment by ielis** [comment]
Hi @abearab, unfortunately MONDO cannot be loaded by `hpo-toolkit` at the moment, but I am planning to support it soon. There are a few issues in the current code that would make working with any more complicated ontology unwieldy. However, MONDO is in the scope of my work and I can imagine supporting it in `hpo-toolkit`s code base.

**Comment by abearab** [comment]
Awesome, looking forward to test it.
